# =============================================================================
# Po_core — Multi-stage Docker build
# =============================================================================
#
# Build:
#   docker build -t po-core:latest .
#
# Run:
#   docker run -p 8000:8000 -e PO_API_KEY=secret po-core:latest
#
# Stages:
#   builder — installs all dependencies into a venv
#   runtime — lean production image (copies venv from builder)
#
# Reproducibility:
#   - The ``python:3.11-slim`` base tag is pinned to a specific digest below.
#     CI verifies the digest via ``docker buildx build --pull=false``.  To
#     refresh the digest, run:
#        ``docker pull python:3.11-slim && docker inspect --format ...``
#     and update ``PYTHON_BASE_DIGEST`` in the FROM line below + the release
#     lock file under ``requirements-release.lock``.
#   - Runtime dependencies are resolved from ``requirements-release.lock``
#     (hash-pinned) when available; otherwise they fall back to
#     ``requirements.txt``.  The lock file is generated by
#     ``tools/generate_release_lock.sh`` and committed.
# =============================================================================

# ---------------------------------------------------------------------------
# Stage 1: builder
# ---------------------------------------------------------------------------
# Pin the base image by digest so a rebuild at a later date produces bytes
# that were verified at commit time.  Update the digest atomically together
# with the lock file.
ARG PYTHON_BASE_DIGEST=sha256:5b8ef70bfc5a33bda23c28a2f43c8c65b5f1e95fce2ec5ea5de9a937e7fac73d
FROM python:3.11-slim@${PYTHON_BASE_DIGEST} AS builder

WORKDIR /build

# System build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Create virtual environment
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install Python dependencies first (layer-cache friendly).  When the release
# lock is present, prefer it so that the exact artifacts from a tagged build
# can be reproduced from any commit.  Otherwise fall back to the best-effort
# ``requirements.txt`` pin.
COPY pyproject.toml requirements.txt ./
COPY requirements-release.lock* ./
RUN pip install --upgrade pip wheel \
    && if [ -f requirements-release.lock ]; then \
           pip install --no-cache-dir --require-hashes \
               -r requirements-release.lock; \
       else \
           pip install --no-cache-dir -r requirements.txt; \
       fi

# Copy source and install package
COPY src/ ./src/
RUN pip install --no-cache-dir --no-deps .

# ---------------------------------------------------------------------------
# Stage 2: runtime
# ---------------------------------------------------------------------------
FROM python:3.11-slim@${PYTHON_BASE_DIGEST} AS runtime

LABEL org.opencontainers.image.title="Po_core REST API" \
      org.opencontainers.image.description="Philosophy-driven AI deliberation via 39 philosopher personas" \
      org.opencontainers.image.source="https://github.com/hiroshitanaka-creator/Po_core" \
      org.opencontainers.image.licenses="AGPL-3.0-or-later"

# Non-root user for security
RUN groupadd --gid 1001 pocore \
    && useradd --uid 1001 --gid pocore --shell /bin/bash --create-home pocore

WORKDIR /app

# Copy venv from builder
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Runtime env vars (override via docker run -e or docker-compose)
ENV PO_HOST=0.0.0.0 \
    PO_PORT=8000 \
    PO_WORKERS=1 \
    PO_LOG_LEVEL=info \
    PO_SKIP_AUTH=false \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# Shadow guard state dir (writable by non-root)
RUN mkdir -p /app/.po_core && chown pocore:pocore /app/.po_core
ENV PO_SHADOW_GUARD_STATE_PATH=/app/.po_core/shadow_guard_state.json

USER pocore

EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:${PO_PORT}/v1/health')"

# Entry point
CMD ["python", "-m", "po_core.app.rest"]
